name: Laravel Docker CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: rest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec laravel-mysql mysqladmin ping -h "127.0.0.1" --silent; do
            sleep 2
          done

      - name: Run Artisan Migrate
        run: docker exec laravel-app php artisan migrate --force

      - name: Run Laravel Tests
        run: docker exec laravel-app php artisan test

      - name: Shut down containers
        if: always()
        run: docker-compose down -v
